[profile.default]
src = 'contracts'
out = "artifacts"
cache_path = "cache"
script = "scripts"
optimizer_runs = 10000000
libs = [
    "lib"
]
remappings = [
    "forge-std/=lib/forge-std/src",
    "@openzeppelin/=contracts/openzeppelin/",
]
fs_permissions = [
    { access = "read-write", path = "blacklist.remote.json"},
    { access = "read-write", path = "test.blacklist.remote.json"}
] # https://book.getfoundry.sh/cheatcodes/fs

[profile.zksync]
src = 'contracts'
libs = ["lib"]
fallback_oz = true
is_system = false
mode = "3"

[rpc_endpoints]
testnet = "https://sepolia.era.zksync.dev"
mainnet = "https://mainnet.era.zksync.io"